import type { Metadata } from "next";
import { Roboto_Condensed, Playfair_Display } from "next/font/google";
import "./globals.css";


const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  weight: ['400','700']
})

export const inter = Roboto_Condensed({
  
  variable: "--font-inter",
  weight: ['400','700']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${playfairDisplay.variable} ${inter.variable}`}>
        {children}
      </body>
    </html>
  );
}