import type { Metadata } from "next";
import { Montserrat} from "next/font/google";
import "./globals.css";

const montserratFont = Montserrat({
  weight: ['400', '700'],
  subsets: ['latin'],

})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${montserratFont.className}`}>
        {children}
      </body>
    </html>
  );
}
