import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <header>
          <div className="site-logo">Universo em Foco</div>
          <p>Explore o incrível mundo da astronomia e descubra segredos do cosmos através de artigos, imagens e muito mais!</p>

          <nav>
            <Link href="/">Ínicio</Link>
            {'|'}
            <Link href="/blog">Blog</Link>
            {'|'}
            <Link href="/loja">Loja</Link>
          </nav>
        </header>

        {children}
      </body>
    </html>
  );
}